CREATE PROCEDURE dbo.HistorificarPrecios
BEGIN

    MERGE INTO FACT_PRECIOS AS target
    USING STG_PRECIOS AS source
    ON target.ID_ARTICULO = source.ID_ARTICULO 
      AND target.FECHA_INICIO_VIGENCIA = source.ID_FECHA
    WHEN MATCHED THEN
        UPDATE
        SET target.FECHA_FIN_VIGENCIA = CASE
            WHEN source.ID_FECHA > COALESCE(target.FECHA_FIN_VIGENCIA, '19000101') THEN source.ID_FECHA
            ELSE target.FECHA_FIN_VIGENCIA
            END
    WHEN NOT MATCHED BY TARGET THEN
        INSERT (FECHA_INICIO_VIGENCIA, FECHA_FIN_VIGENCIA, ID_ARTICULO, PRECIO_COSTE, PRECIO_VENTA)
        VALUES (source.ID_FECHA, NULL, source.ID_ARTICULO, source.PRECIO_COSTE, source.PRECIO_VENTA); 
END;